---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: fixture
    run_list:
      - recipe[golang-web::fixture]
      - recipe[golang-web::deploy]
    attributes:
      deploy:
        s3zip:
          deploy_to: "/apps/s3zip"
